name = "EasyVega"
uuid = "c061e33b-2451-47b3-8b22-ec396b8f69c0"
authors = ["frederic.testard <frederic.testard@sgcib.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
